# Generated by Django 6.0 on 2026-04-08 04:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_player_bio_player_photo_user_avatar_manager_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mixes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MixLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gain', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layers', to='mix.mix')),
                ('sound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mix_layers', to='core.sound')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mix_layers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
