from django.test import TestCase
from django.urls import reverse

from core.models import Sound


class CardDemoTests(TestCase):
    @classmethod
    def setUpTestData(cls):
        for index in range(1, 10):
            Sound.objects.create(
                published=True,
                title=f"Demo sound {index}",
                artist_legacy=f"Artist {index}",
                file=f"sounds/demo-{index}.wav",
                art=f"sound_arts/demo-{index}.jpg",
                flavor=f"Description {index}",
                embeddings=[0.0] * 5,
            )

    def test_page_uses_the_first_eight_sounds(self):
        response = self.client.get(reverse("card_demo:index"))

        self.assertEqual(response.status_code, 200)
        self.assertTemplateUsed(response, "card_demo/index.html")
        self.assertEqual(
            [sound["sound_title"] for sound in response.context["sounds"]],
            [f"Demo sound {index}" for index in range(1, 9)],
        )
        self.assertTrue(all(sound["gain"] == 50 for sound in response.context["sounds"]))
        self.assertNotContains(response, "Demo sound 9")

    def test_page_is_ui_only(self):
        response = self.client.get(reverse("card_demo:index"))

        self.assertContains(response, "data-card-demo")
        self.assertContains(response, "data-card-demo-tools")
        self.assertContains(response, 'data-theme="dim"')
        self.assertContains(response, 'data-light-mode="true"')
        self.assertNotContains(response, "data-card-theme-toggle")
        self.assertNotContains(response, "Activate light mode")
        self.assertNotContains(response, "toggleLightMode")
        self.assertContains(response, "data-card-hue-slider")
        self.assertContains(response, "data-card-brightness-slider")
        self.assertContains(response, "data-ring-paper-hue-slider")
        self.assertContains(response, "data-ring-paper-brightness-slider")
        self.assertContains(response, "Ring + paper")
        self.assertNotContains(response, "data-page-hue-slider")
        self.assertContains(response, "data-card-width-slider")
        self.assertContains(response, "data-card-height-slider")
        self.assertContains(response, ':min="minimumCardWidthIn"')
        self.assertContains(response, ':max="maximumCardWidthIn"')
        self.assertContains(response, ':min="minimumCardHeightIn"')
        self.assertContains(response, ':max="maximumCardHeightIn"')
        self.assertContains(response, ':value="effectiveCardWidthIn"')
        self.assertContains(response, ':value="effectiveCardHeightIn"')
        self.assertContains(response, ':aria-valuetext="`${effectiveCardWidthIn.toFixed(2)} inches`"')
        self.assertContains(response, ':aria-valuetext="`${effectiveCardHeightIn.toFixed(2)} inches`"')
        self.assertContains(response, "data-card-scale-slider")
        self.assertContains(response, 'min="50"')
        self.assertContains(response, 'max="200"')
        self.assertContains(response, "data-card-gap-slider")
        self.assertContains(response, "data-print-sheet")
        self.assertContains(response, "data-print-grid-island")
        self.assertContains(response, "data-print-card-slot")
        self.assertContains(response, "US Letter print sheet preview")
        self.assertContains(response, "width: 8.5in")
        self.assertContains(response, "height: 11in")
        self.assertContains(response, "padding: var(--island-padding-y) var(--island-padding-x)")
        self.assertContains(response, "--island-padding-x")
        self.assertContains(response, "--island-padding-y")
        self.assertContains(response, "background-color: white")
        self.assertContains(response, "background-color: var(--page-surface)")
        self.assertContains(response, "--effective-card-width")
        self.assertContains(response, "--effective-card-height")
        self.assertContains(response, "width: var(--effective-card-width)")
        self.assertContains(response, "width: var(--printed-card-width)")
        self.assertContains(response, "grid-template-columns: repeat(var(--sheet-columns), var(--printed-card-width))")
        self.assertContains(response, "transform: scale(var(--card-scale))")
        self.assertContains(response, "data-print-guide")
        self.assertContains(response, "data-guide-toggle")
        self.assertContains(response, "data-guide-width-slider")
        self.assertContains(response, "data-guide-height-slider")
        self.assertContains(response, "width: var(--guide-width)")
        self.assertContains(response, "height: var(--guide-height)")
        self.assertContains(response, "left: var(--guide-center-x)")
        self.assertContains(response, "top: var(--guide-center-y)")
        self.assertContains(response, "height: var(--effective-card-height)")
        self.assertNotContains(response, "--card-scale-x")
        self.assertNotContains(response, "--card-scale-y")
        self.assertNotContains(response, "transform: scale(var(--card-scale-x), var(--card-scale-y))")
        self.assertContains(response, "--card-shell: hsl(var(--card-hue) 34% var(--card-brightness))")
        self.assertContains(response, "--page-surface: hsl(var(--ring-hue) 18% var(--ring-brightness))")
        self.assertNotContains(response, "--page-hue")
        self.assertContains(response, "border-radius: 1.125rem")
        self.assertContains(response, "box-shadow: 0 0 0 8px var(--ring-surface)")
        self.assertContains(response, "ring-8")
        self.assertNotContains(response, "ring-[1.5rem]")
        self.assertContains(response, "data-card-demo-sounds")
        self.assertContains(response, "data-card-demo-indicator")
        self.assertContains(response, "data-card-demo-indicator-text")
        self.assertContains(response, "--card-indicator-height")
        self.assertContains(response, "--card-media-inset: 1.5rem")
        self.assertContains(response, "--card-media-top: 1.75rem")
        self.assertContains(response, "--card-flavor-inset: 1rem")
        self.assertContains(response, "margin: var(--card-media-top) var(--card-media-inset) 0")
        self.assertContains(response, "width: fit-content")
        self.assertContains(response, "max-width: calc(100% - 2rem)")
        self.assertContains(response, "min-w-0 max-w-full truncate")
        self.assertContains(response, "data-flavor-text-input")
        self.assertContains(response, "data-flavor-size-slider")
        self.assertContains(response, "data-flavor-overlay-upload")
        self.assertContains(response, 'accept="image/*,.svg"')
        self.assertContains(response, "data-flavor-overlay-status")
        self.assertContains(response, "data-flavor-overlay-error")
        self.assertContains(response, "data-flavor-overlay-tint-hue-slider")
        self.assertContains(response, "data-flavor-overlay-tint-brightness-slider")
        self.assertContains(response, "data-flavor-overlay-tint-strength-slider")
        self.assertContains(response, "data-card-demo-flavor-box")
        self.assertContains(response, "data-card-demo-flavor-overlay-shell")
        self.assertContains(response, "data-card-demo-flavor-overlay")
        self.assertContains(response, "data-card-demo-flavor-overlay-tint")
        self.assertContains(response, "min-h-0 flex-1 overflow-hidden")
        self.assertContains(response, "margin: 0 var(--card-flavor-inset) 1rem")
        self.assertNotContains(response, "--card-media-inset: clamp(")
        self.assertContains(response, 'class="relative h-full overflow-hidden px-4 py-2"')
        self.assertContains(response, "absolute inset-0 h-full w-full object-contain")
        self.assertContains(response, 'aria-label="Flavor text area"')
        self.assertContains(response, "data-indicator-text-input")
        self.assertContains(response, "data-indicator-size-slider")
        self.assertContains(response, "data-indicator-spacing-slider")
        self.assertContains(response, "data-indicator-centered-toggle")
        self.assertContains(response, "data-master-text-input")
        self.assertContains(response, "data-master-text-size-slider")
        self.assertContains(response, "data-master-text-spacing-slider")
        self.assertContains(response, "data-card-demo-master-text")
        self.assertContains(response, "font-stretch: normal")
        self.assertContains(response, "bg-[#f3f4f6]")
        self.assertContains(response, 'style="color: #2d2d2d"')
        self.assertContains(response, "data-left-arrow-toggle")
        self.assertContains(response, "data-right-arrow-toggle")
        self.assertContains(response, "data-bottom-arrow-toggle")
        self.assertContains(response, "data-bottom-arrow-slider")
        self.assertContains(response, 'x-show="showLeftArrow"')
        self.assertContains(response, 'x-show="showRightArrow"')
        self.assertContains(response, 'x-show="showBottomArrow"')
        self.assertContains(response, "data-card-demo-bottom-arrow")
        self.assertContains(response, "--card-side-arrow-size")
        self.assertContains(response, "--card-side-arrow-offset")
        self.assertContains(response, 'left: calc(-1 * var(--card-side-arrow-offset))')
        self.assertContains(response, 'right: calc(-1 * var(--card-side-arrow-offset))')
        self.assertContains(response, "transform: translateY(-50%) scaleX(0.75) scaleY(1.5)")
        self.assertContains(response, "transform: translate(-50%, -4rem) scaleX(1.25) scaleY(0.75)")
        self.assertContains(response, "data-card-demo-media")
        self.assertContains(response, "data-card-demo-artwork-frame")
        self.assertContains(response, "data-card-demo-artwork-viewport")
        self.assertContains(response, "data-card-demo-slider-row")
        self.assertContains(response, "data-card-demo-slider-track-shell")
        self.assertContains(response, "data-card-demo-volume-track")
        self.assertContains(response, "gap: 0.75rem")
        self.assertContains(response, "padding-inline: 1.375rem")
        self.assertContains(response, "width: 1.5rem")
        self.assertContains(response, "height: 1.5rem")
        self.assertContains(response, "padding: 1.5rem 0.5rem")
        self.assertContains(response, "width: 5.5rem")
        self.assertContains(response, "height: 5.5rem")
        self.assertNotContains(response, "gap: clamp(0.25rem, 3.75cqw, 0.75rem)")
        self.assertNotContains(response, "width: clamp(0.875rem, 7.5cqw, 1.5rem)")
        self.assertContains(response, "aspect-ratio: 1 / 1")
        self.assertContains(response, "--card-side-arrow-size: 5rem")
        self.assertContains(response, "--card-side-arrow-offset: 2.875rem")
        self.assertContains(response, "data-artwork-upload")
        self.assertContains(response, 'accept="image/*"')
        self.assertContains(response, "absolute inset-0 h-full w-full object-cover object-center")
        self.assertContains(response, "data-artwork-error")
        self.assertContains(response, "data-artwork-text-toggle")
        self.assertContains(response, "data-artwork-title-input")
        self.assertContains(response, "data-artist-name-input")
        self.assertContains(response, "data-artwork-text-size-slider")
        self.assertContains(response, "data-card-demo-artwork-text")
        self.assertContains(response, 'x-show="showArtworkText"')
        self.assertContains(response, "data-like-button-toggle")
        self.assertContains(response, "data-card-demo-like")
        self.assertContains(response, "data-card-demo-like-icon")
        self.assertContains(response, "fill-red-500 text-red-500")
        self.assertContains(response, "width: 62.5%")
        self.assertContains(response, "height: 62.5%")
        self.assertContains(response, 'x-show="showLikeButton"')
        self.assertContains(response, 'aria-label="Previous carousel panel"')
        self.assertContains(response, 'aria-label="Next carousel panel"')
        self.assertContains(response, 'aria-label="Current layer volume"')
        self.assertContains(response, "fill-current opacity-0", count=2)
        self.assertContains(response, "Mute this layer")
        self.assertContains(response, "Isolate this layer")
        self.assertContains(response, "data-card-demo-master")
        self.assertContains(response, "data-card-demo-master-shell")
        self.assertContains(response, "data-card-demo-artwork")
        self.assertContains(response, "overflow-hidden rounded-t-2xl")
        self.assertNotContains(response, 'x-text="index + 1"')
        self.assertNotContains(response, "currentLayer?.sound_title")
        self.assertNotContains(response, "currentLayer?.sound_artist")
        self.assertNotContains(response, "currentLayer?.tags")
        self.assertNotContains(response, "currentLayer?.flavor")
        self.assertNotContains(response, "No flavor text yet.")
        self.assertNotContains(response, "Add to favourite sounds")
        self.assertNotContains(response, "Remove from favourite sounds")
        self.assertNotContains(response, ':disabled="isFirst"')
        self.assertNotContains(response, "join-item")
        self.assertNotContains(response, 'aria-label="Lower all Sounds"')
        self.assertNotContains(response, "Pause this Cosound")
        self.assertNotContains(response, 'aria-label="Save this Cosound"')
        self.assertNotContains(response, 'aria-label="Raise all Sounds"')
        self.assertNotContains(response, 'id="card-demo-deck"')
        self.assertNotContains(response, 'id="card-demo-header"')
        self.assertNotContains(response, 'id="card-demo-figure"')
        self.assertNotContains(response, 'id="card-demo-body"')
        self.assertNotContains(response, 'id="card-demo-master"')
        self.assertNotContains(response, "<audio")
        self.assertNotContains(response, "sound_file")
        self.assertNotContains(response, "data-cosound-mixer-root")
        self.assertNotContains(response, "hx-post")
