# Generated by Django 6.0 on 2026-05-02 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
