# Generated by Django 6.0 on 2026-04-10 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_player_bio_player_photo_user_avatar_manager_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sound',
            name='art',
            field=models.ImageField(blank=True, null=True, upload_to='sound_arts'),
        ),
        migrations.AddField(
            model_name='sound',
            name='flavor',
            field=models.TextField(blank=True, null=True),
        ),
    ]
