# Generated by Django 6.0 on 2026-05-03 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_player_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='bio',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
