# Generated by Django 6.0 on 2026-04-10 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sound_art_sound_flavor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sound',
            name='art',
            field=models.ImageField(blank=True, null=True, upload_to='sound_arts/'),
        ),
    ]
