# Generated by Django 6.0 on 2026-05-03 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_player_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sound',
            name='flavor',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
