# Generated by Django 6.0 on 2026-09-14 23:36

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_player_sleeping'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlgorithmDecision',
            fields=[
                ('decision_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('policy_version', models.CharField(max_length=64)),
                ('configuration', models.JSONField(default=dict)),
                ('decided_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('previous_layers', models.JSONField(default=list)),
                ('selected_layers', models.JSONField(default=list)),
                ('active_listener_ids', models.JSONField(default=list)),
                ('input_snapshot', models.JSONField(default=dict)),
                ('outcome', models.CharField(max_length=64)),
                ('selected_score', models.FloatField(blank=True, null=True)),
                ('selected_action_probability', models.FloatField(default=1.0)),
                ('exploration', models.BooleanField(default=False)),
                ('trace', models.JSONField(default=dict)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='algorithm_decisions', to='core.player')),
            ],
            options={
                'ordering': ['decided_at', 'decision_id'],
            },
        ),
        migrations.CreateModel(
            name='PlaybackExposure',
            fields=[
                ('exposure_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mix_key', models.CharField(db_index=True, max_length=255)),
                ('layers', models.JSONField(default=list)),
                ('commanded_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('transition_seconds', models.FloatField(blank=True, null=True)),
                ('estimated_audible_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('commanded', 'Commanded'), ('player_acknowledged', 'Player acknowledged'), ('ended', 'Ended'), ('failed', 'Failed')], default='commanded', max_length=32)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('opening_decision', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='opened_exposure', to='core.algorithmdecision')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playback_exposures', to='core.player')),
            ],
            options={
                'ordering': ['commanded_at', 'exposure_id'],
            },
        ),
        migrations.AddField(
            model_name='player',
            name='current_exposure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_for_players', to='core.playbackexposure'),
        ),
    ]
