# Generated by Django 6.0 on 2026-09-15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("core", "0008_algorithmdecision_playbackexposure_and_more")]

    operations = [
        migrations.AddField(
            model_name="localpost",
            name="algorithm_active_listener_minutes",
            field=models.PositiveIntegerField(
                default=5,
                help_text="A listener's votes influence the mix for this long.",
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="active listener window (minutes)",
            ),
        ),
        migrations.AddField(
            model_name="localpost",
            name="algorithm_disagreement_penalty",
            field=models.FloatField(
                default=0.25,
                help_text="Higher values favor consensus over mixes that split the room.",
                validators=[django.core.validators.MinValueValidator(0.0)],
                verbose_name="disagreement penalty",
            ),
        ),
        migrations.AddField(
            model_name="localpost",
            name="algorithm_exploration_probability",
            field=models.FloatField(
                default=0.5,
                help_text="Chance of trying another highly ranked mix, from 0 to 1.",
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1.0),
                ],
                verbose_name="exploration probability",
            ),
        ),
        migrations.AddField(
            model_name="localpost",
            name="algorithm_exploration_size",
            field=models.PositiveIntegerField(
                default=5,
                help_text="Number of top-ranked candidates that exploration may choose from.",
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="exploration pool size",
            ),
        ),
        migrations.AddField(
            model_name="localpost",
            name="baseline",
            field=models.ForeignKey(
                blank=True,
                help_text=(
                    "Optional fallback when no listener evidence or valid mix exists. "
                    "The baseline must also be in this post's sound collection."
                ),
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="baseline_posts",
                to="core.sound",
                verbose_name="baseline",
            ),
        ),
        migrations.AddField(
            model_name="localpost",
            name="algorithm_max_layers",
            field=models.PositiveSmallIntegerField(
                default=5,
                help_text=(
                    "Maximum number of sounds in a generated mix. Larger values make "
                    "the initial candidate search grow quickly."
                ),
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
                verbose_name="maximum layers",
            ),
        ),
        migrations.AddField(
            model_name="localpost",
            name="algorithm_maximum_stay_seconds",
            field=models.PositiveIntegerField(
                blank=True,
                default=180,
                help_text="Force eventual rotation after this long. Leave blank for no limit.",
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="maximum stay (seconds)",
            ),
        ),
        migrations.AddField(
            model_name="localpost",
            name="algorithm_min_layers",
            field=models.PositiveSmallIntegerField(
                default=2,
                help_text="Minimum number of sounds in a generated mix.",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
                verbose_name="minimum layers",
            ),
        ),
        migrations.AddField(
            model_name="localpost",
            name="algorithm_minimum_hold_seconds",
            field=models.PositiveIntegerField(
                default=120,
                help_text="Keep a selected mix for at least this long before reconsidering it.",
                verbose_name="minimum hold (seconds)",
            ),
        ),
        migrations.AddField(
            model_name="localpost",
            name="algorithm_refresh_interval_seconds",
            field=models.PositiveIntegerField(
                default=30,
                help_text="How often the server re-runs this post's algorithm (minimum 5).",
                validators=[django.core.validators.MinValueValidator(5)],
                verbose_name="refresh interval (seconds)",
            ),
        ),
        migrations.AddField(
            model_name="localpost",
            name="algorithm_sleep_after_minutes",
            field=models.PositiveIntegerField(
                default=180,
                help_text="Put this post's player to sleep after this much inactivity.",
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="sleep after (minutes)",
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="state_refresh_interval_seconds",
            field=models.PositiveIntegerField(
                default=30,
                help_text=(
                    "How often the physical player checks for missed state changes "
                    "(minimum 5). Live updates still arrive immediately."
                ),
                validators=[django.core.validators.MinValueValidator(5)],
                verbose_name="fallback state poll interval (seconds)",
            ),
        ),
        migrations.AddConstraint(
            model_name="player",
            constraint=models.CheckConstraint(
                condition=models.Q(state_refresh_interval_seconds__gte=5),
                name="player_state_refresh_at_least_5",
            ),
        ),
        migrations.AddConstraint(
            model_name="localpost",
            constraint=models.CheckConstraint(
                condition=models.Q(algorithm_refresh_interval_seconds__gte=5),
                name="localpost_algorithm_refresh_at_least_5",
            ),
        ),
        migrations.AddConstraint(
            model_name="localpost",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(algorithm_min_layers__gte=1)
                    & models.Q(algorithm_min_layers__lte=5)
                    & models.Q(algorithm_max_layers__gte=1)
                    & models.Q(algorithm_max_layers__lte=5)
                    & models.Q(
                        algorithm_min_layers__lte=models.F("algorithm_max_layers")
                    )
                ),
                name="localpost_algorithm_layer_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="localpost",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(algorithm_active_listener_minutes__gte=1)
                    & models.Q(
                        algorithm_sleep_after_minutes__gte=models.F(
                            "algorithm_active_listener_minutes"
                        )
                    )
                ),
                name="localpost_algorithm_listener_windows",
            ),
        ),
        migrations.AddConstraint(
            model_name="localpost",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(algorithm_maximum_stay_seconds__isnull=True)
                    | (
                        models.Q(algorithm_maximum_stay_seconds__gte=1)
                        & models.Q(
                            algorithm_maximum_stay_seconds__gte=models.F(
                                "algorithm_minimum_hold_seconds"
                            )
                        )
                    )
                ),
                name="localpost_algorithm_stay_after_hold",
            ),
        ),
        migrations.AddConstraint(
            model_name="localpost",
            constraint=models.CheckConstraint(
                condition=models.Q(algorithm_disagreement_penalty__gte=0),
                name="localpost_algorithm_nonnegative_penalty",
            ),
        ),
        migrations.AddConstraint(
            model_name="localpost",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(algorithm_exploration_probability__gte=0)
                    & models.Q(algorithm_exploration_probability__lte=1)
                ),
                name="localpost_algorithm_probability_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="localpost",
            constraint=models.CheckConstraint(
                condition=models.Q(algorithm_exploration_size__gte=1),
                name="localpost_algorithm_exploration_size",
            ),
        ),
    ]
