# Generated by Django 6.0 on 2026-09-15

import core.models
import core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("core", "0009_localpost_algorithm_parameters")]

    operations = [
        migrations.AddField(
            model_name="localpost",
            name="chime",
            field=models.FileField(
                blank=True,
                help_text=(
                    "Played by this post's player when a listener vote is received. "
                    "Maximum 5 seconds and 5 MB. Supported formats: WAV, FLAC, "
                    "OGG, MP3, and AIFF."
                ),
                max_length=255,
                upload_to=core.models.chime_upload_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "wav",
                            "flac",
                            "ogg",
                            "mp3",
                            "aif",
                            "aiff",
                        ]
                    ),
                    core.validators.validate_chime,
                ],
                verbose_name="vote confirmation chime",
            ),
        ),
    ]
