# Generated by Django 6.0 on 2026-09-16 10:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_localpost_playerprogram_and_player_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprogram',
            name='chime_volume',
            field=models.FloatField(default=0.5, help_text='How loud the chime is relative to the mix it interrupts, from 0 to 1. The player scales the chime by this fraction of the running loudness of whatever it is already playing, so the acknowledgement keeps its prominence in a quiet room and a dense one alike. 0 silences it.', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='chime volume'),
        ),
        migrations.AddConstraint(
            model_name='playerprogram',
            constraint=models.CheckConstraint(condition=models.Q(('chime_volume__gte', 0), ('chime_volume__lte', 1)), name='playerprogram_chime_volume_range'),
        ),
    ]
