# Generated by Django 6.0 on 2026-09-18 21:08

import django.db.models.deletion
import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_playerprogram_chime_volume_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListenerPresence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visited_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('listener', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.listener')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.player')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('player', 'listener'), name='unique_listener_presence')],
            },
        ),
        migrations.AlterField(
            model_name='playerprogram',
            name='algorithm_active_listener_minutes',
            field=models.PositiveIntegerField(default=5, help_text="A listener's visits or votes influence the mix for this long.", validators=[django.core.validators.MinValueValidator(1)], verbose_name='active listener window (minutes)'),
        ),
    ]
