# Generated by Django 6.0 on 2026-09-23 08:32

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_sound_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='sound',
            name='duration',
            field=models.FloatField(blank=True, help_text='Seconds, as stored.', null=True),
        ),
        migrations.AddField(
            model_name='sound',
            name='loop_crossfade',
            field=models.FloatField(blank=True, help_text='Seconds of the tail folded into the head at the seam.', null=True),
        ),
        migrations.AddField(
            model_name='sound',
            name='loudness_gain_db',
            field=models.FloatField(blank=True, help_text='Gain applied to reach it, in dB.', null=True),
        ),
        migrations.AddField(
            model_name='sound',
            name='loudness_lufs',
            field=models.FloatField(blank=True, help_text='Integrated loudness of the stored file (LUFS).', null=True),
        ),
        migrations.AddField(
            model_name='sound',
            name='seamless',
            field=models.BooleanField(default=False, help_text='Baked into a seamless loop when its artist saved it: it plays back to back with no join, so a new mix starts it as one copy with no gaps.'),
        ),
        migrations.AddField(
            model_name='sound',
            name='trim_end',
            field=models.FloatField(blank=True, help_text='Where the kept audio ended in the upload, in seconds.', null=True),
        ),
        migrations.AddField(
            model_name='sound',
            name='trim_start',
            field=models.FloatField(blank=True, help_text='Where the kept audio began in the upload, in seconds.', null=True),
        ),
        migrations.AddField(
            model_name='soundlayer',
            name='cycle_rest',
            field=models.DecimalField(decimal_places=1, default=Decimal('0.0'), help_text='Seconds of silence after each cycle; 0 plays without end.', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('300'))]),
        ),
        migrations.AddField(
            model_name='soundlayer',
            name='phase_hold',
            field=models.PositiveSmallIntegerField(default=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(64)]),
        ),
        migrations.AddField(
            model_name='soundlayer',
            name='phase_hold_alt',
            field=models.PositiveSmallIntegerField(default=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(64)]),
        ),
        migrations.AddField(
            model_name='soundlayer',
            name='phase_step',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='How far the second copy slips at each shift, as a fraction of a period.', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('0.5'))]),
        ),
        migrations.AddField(
            model_name='soundlayer',
            name='playback_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.25')), django.core.validators.MaxValueValidator(Decimal('2.00'))]),
        ),
        migrations.AddField(
            model_name='soundlayer',
            name='repetitions',
            field=models.PositiveSmallIntegerField(default=1, help_text='Periods per cycle.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(16)]),
        ),
        migrations.AddField(
            model_name='soundlayer',
            name='second_copy',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='soundlayer',
            name='start_delay',
            field=models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('120'))]),
        ),
        migrations.AddField(
            model_name='soundlayer',
            name='stretch',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.75'), help_text='Spacing: a pass repeats every length × this. 1 is back to back.', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.50')), django.core.validators.MaxValueValidator(Decimal('4.00'))]),
        ),
    ]
