# Generated by Django 6.0 on 2026-09-23 09:36

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_soundlayer_timing_and_baked_sounds'),
    ]

    operations = [
        migrations.AddField(
            model_name='soundlayer',
            name='playback_rate_b',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="The second copy's rate, so the layer alternates two pitches. Empty is the first's.", max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.25')), django.core.validators.MaxValueValidator(Decimal('2.00'))]),
        ),
        migrations.AddField(
            model_name='soundlayer',
            name='take_turns',
            field=models.BooleanField(default=False, help_text='The copies never overlap: each waits for the other to finish, then the gap.'),
        ),
        migrations.AddField(
            model_name='soundlayer',
            name='turn_gap',
            field=models.DecimalField(decimal_places=1, default=Decimal('0.0'), help_text="Seconds of silence between the copies' turns.", max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('60'))]),
        ),
    ]
