# Generated by Django 6.0 on 2026-01-26 00:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sound_playeraccount_player'),
        ('voter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sound')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_links', to='voter.voter')),
            ],
        ),
        migrations.AddField(
            model_name='voter',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', through='voter.Favorite', to='core.sound'),
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(fields=('voter', 'sound'), name='unique_favorite_voter_sound'),
        ),
    ]
