# Generated by Django 6.0 on 2026-04-09 06:48

import core.models
import django.core.serializers.json
import django.db.models.deletion
import django_pydantic_field.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_player_bio_player_photo_user_avatar_manager_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cosound', django_pydantic_field.fields.PydanticSchemaField(config=None, encoder=django.core.serializers.json.DjangoJSONEncoder, schema=core.models.Cosound)),
                ('value', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.player')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.listener')),
            ],
        ),
    ]
