# Generated by Django 6.0 on 2026-09-14 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_algorithmdecision_playbackexposure_and_more'),
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='attribution_quality',
            field=models.CharField(choices=[('unattributed', 'Unattributed'), ('server_current', 'Server current exposure'), ('transition_uncertain', 'Player transition uncertain'), ('player_acknowledged', 'Player acknowledged exposure')], default='unattributed', max_length=32),
        ),
        migrations.AddField(
            model_name='vote',
            name='exposure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='votes', to='core.playbackexposure'),
        ),
    ]
