# Generated by Django 6.0 on 2026-05-01 00:00

from django.db import migrations


def _get_columns(schema_editor, table):
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        try:
            description = connection.introspection.get_table_description(cursor, table)
        except Exception:
            return set()
    return {getattr(col, "name", col[0]) for col in description}


def rename_cosound_column(apps, schema_editor):
    Vote = apps.get_model("vote", "Vote")
    table = Vote._meta.db_table
    columns = _get_columns(schema_editor, table)
    if "cosound_id" in columns or "cosound" not in columns:
        return
    table_name = schema_editor.quote_name(table)
    old_name = schema_editor.quote_name("cosound")
    new_name = schema_editor.quote_name("cosound_id")
    schema_editor.execute(
        f"ALTER TABLE {table_name} RENAME COLUMN {old_name} TO {new_name}"
    )


def reverse_rename_cosound_column(apps, schema_editor):
    Vote = apps.get_model("vote", "Vote")
    table = Vote._meta.db_table
    columns = _get_columns(schema_editor, table)
    if "cosound" in columns or "cosound_id" not in columns:
        return
    table_name = schema_editor.quote_name(table)
    old_name = schema_editor.quote_name("cosound_id")
    new_name = schema_editor.quote_name("cosound")
    schema_editor.execute(
        f"ALTER TABLE {table_name} RENAME COLUMN {old_name} TO {new_name}"
    )


class Migration(migrations.Migration):

    dependencies = [
        ("vote", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(rename_cosound_column, reverse_rename_cosound_column),
    ]
