# Generated by Django 6.0 on 2026-05-01 00:00

from django.db import migrations


def _get_udt_name(schema_editor, table, column):
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            "SELECT udt_name FROM information_schema.columns WHERE table_name = %s AND column_name = %s",
            [table, column],
        )
        row = cursor.fetchone()
    return row[0] if row else None


def alter_cosound_id_type(apps, schema_editor):
    Vote = apps.get_model("vote", "Vote")
    table = Vote._meta.db_table
    if _get_udt_name(schema_editor, table, "cosound_id") != "jsonb":
        return
    table_name = schema_editor.quote_name(table)
    column_name = schema_editor.quote_name("cosound_id")
    schema_editor.execute(f"""
        ALTER TABLE {table_name}
        ALTER COLUMN {column_name} TYPE bigint
        USING (
            CASE
                WHEN jsonb_typeof({column_name}) = 'number'
                    THEN ({column_name}::text)::bigint
                WHEN jsonb_typeof({column_name}) = 'string'
                     AND ({column_name}::text) ~ '^\"[0-9]+\"$'
                    THEN (trim(both '"' from {column_name}::text))::bigint
                WHEN jsonb_typeof({column_name}) = 'object'
                     AND ({column_name}->>'id') ~ '^[0-9]+$'
                    THEN ({column_name}->>'id')::bigint
                WHEN jsonb_typeof({column_name}) = 'object'
                     AND ({column_name}->>'cosound_id') ~ '^[0-9]+$'
                    THEN ({column_name}->>'cosound_id')::bigint
                ELSE NULL
            END
        )
        """)


class Migration(migrations.Migration):

    dependencies = [
        ("vote", "0002_fix_vote_cosound_column"),
    ]

    operations = [
        migrations.RunPython(alter_cosound_id_type, migrations.RunPython.noop),
    ]
