# Generated by Django 6.0 on 2026-05-04 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0003_fix_vote_cosound_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='section',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
